# Define the user and group under which NGINX will run (www-data is the standard for Debian/Ubuntu)
user www-data;

# Define the location of the NGINX PID file (for process management)
pid /run/nginx.pid; 

events { 
	# Maximum number of simultaneous connections per worker
	worker_connections 1024;
}

http {
	# mime.types is essential for the browser to recognize CSS/JS files and for the website to render correctly
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	server {
		# Listen only on port 443 with SSL encryption enabled (IPv4 and IPv6)
		listen 443 ssl; # IPv4
		listen [::]:443 ssl; #[::] means IPv6

		# The domain name configured in the /etc/hosts file
		server_name ozamora-.42.fr;

		# Absolute paths of the SSL certificate and key inside the container
		ssl_certificate /etc/nginx/ssl/inception.crt;
		ssl_certificate_key /etc/nginx/ssl/inception.key;

		# Restrict the connection strictly to modern and secure TLS protocols
		ssl_protocols TLSv1.2 TLSv1.3;

		# The shared root directory where WordPress will store the physical website
		root /var/www/html;
		index index.php index.html index.htm;

		# Handle WordPress routes (internal redirection for permalinks)
		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		# Critical block: FastCGI redirection for PHP script requests
		location ~ \.php$ {
			# If the requested PHP file does not physically exist, return a 404 error (prevents security exploits)
			try_files $uri =404;

			# 127.0.0.11 is the IP of Docker's default internal DNS server
			resolver 127.0.0.11 valid=30s ipv6=off;
			
			# We define the destination in a var and use it in fastcgi_pass to avoid issues with DNS resolution
			set $upstream_wordpress wordpress:9000;
			fastcgi_pass $upstream_wordpress;
			
			# Include the default FastCGI parameters of NGINX
			include fastcgi_params;

			# Define the mandatory SCRIPT_FILENAME variable so that PHP-FPM knows which exact script to execute
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		}
	}
}
