# Definir el usuario y grupo con el que NGINX se ejecutará (www-data es el estándar de Debian/Ubuntu)
user www-data;

# Definir la ubicación del archivo PID de NGINX (para gestión de procesos)
pid /run/nginx.pid; 

events { 
    # Cantidad máxima de conexiones simultáneas por worker
    worker_connections 1024;
}

http {
    # mime.types es indispensable para que el navegador reconozca archivos CSS/JS y la web no se renderice rota
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        # Escuchar únicamente en el puerto 443 con encriptación SSL activa (IPv4 e IPv6)
        listen 443 ssl;
        listen [::]:443 ssl; #[::] indica que también se aceptan conexiones IPv6

        # Nombre de tu dominio configurado en el archivo /etc/hosts
        server_name ozamora.42.fr;

        # Rutas absolutas del certificado y la clave SSL dentro del contenedor
        ssl_certificate /etc/ssl/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        # Restringir la conexión estrictamente a protocolos TLS modernos y seguros
        ssl_protocols TLSv1.2 TLSv1.3;

        # Directorio raíz compartido donde WordPress almacenará la web física
        root /var/www/html;
        index index.php index.html index.htm;

        # Manejar las rutas de WordPress (redirección interna para permalinks)
        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # Bloque crítico: Redirección FastCGI para peticiones de scripts PHP 
        location ~ \.php$ {
            # Si el archivo PHP solicitado no existe físicamente, devolver error 404 (evita exploits de seguridad)
            try_files $uri =404;

            # 127.0.0.11 es la IP del servidor DNS interno por defecto de Docker
            resolver 127.0.0.11 valid=30s ipv6=off;
            
            # Definimos el destino en una variable
            set $upstream_wordpress wordpress:9000;

            # Pasamos la variable en lugar del host estático
            fastcgi_pass $upstream_wordpress;
            
            # Incluir los parámetros por defecto de FastCGI de NGINX
            include fastcgi_params;

            # Definir la variable obligatoria SCRIPT_FILENAME para que PHP-FPM sepa qué script exacto ejecutar
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
