services:
  # Database Service (MariaDB)
  # MariaDB service that will serve as the database backend for WordPress.
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    restart: always
    env_file:
      - .env
    secrets:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    expose:
      - "3306"

  # Application Service (PHP-FPM 8.2)
  # FastCGI Process Manager for PHP 8.2, which will handle PHP requests from the NGINX reverse proxy.
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - MYSQL_PASSWORD
      - WORDPRESS_USER_PASS
      - WORDPRESS_ADMIM_PASS
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    expose:
      - "9000"

  # Web Server Service (Reverse Proxy)
  # Reverse proxy service that forwards requests to the WordPress container.
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network

# Bridge Network
# Allows communication between the containers, isolated from the host network.
networks:
  inception_network:
    name: inception_network
    driver: bridge

# Volumes
# Allows data persistence even if the containers are removed or recreated.
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ozamora-/data/mariadb'

  wordpress_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ozamora-/data/wordpress'

# Secrets
# Securely store sensitive information like passwords, which can be accessed by the containers.
secrets:
  MYSQL_ROOT_PASSWORD:
    file: ../secrets/MYSQL_ROOT_PASSWORD.txt
  MYSQL_PASSWORD:
    file: ../secrets/MYSQL_PASSWORD.txt
  WORDPRESS_USER_PASS:
    file: ../secrets/WORDPRESS_USER_PASS.txt
  WORDPRESS_ADMIM_PASS:
    file: ../secrets/WORDPRESS_ADMIM_PASS.txt