[www]
; Usuario y grupo por defecto del sistema Debian para ejecutar procesos PHP
user = www-data
group = www-data

; Redirigir la escucha a cualquier IP en el puerto 9000 (TCP) para que Docker lo resuelva
listen = 0.0.0.0:9000

; Asignar permisos al socket de red
listen.owner = www-data
listen.group = www-data

; Configuración de rendimiento del gestor de procesos (Dynamic para balanceo de memoria)
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Evitar que PHP-FPM borre las variables de entorno del contenedor, lo que permite que WordPress acceda a ellas
clear_env = no