[www]
; Default user and group for running PHP processes on Debian
user = www-data
group = www-data

; Redirect listening to any IP on port 9000 (TCP) so that Docker can resolve it
listen = 0.0.0.0:9000

; Define the owner and group of the socket file to ensure proper permissions for NGINX to communicate with PHP-FPM
listen.owner = www-data
listen.group = www-data

; Performance configuration of the process manager
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Prevent PHP-FPM from clearing the container's environment variables, allowing WordPress to access them
clear_env = no